-- Nivel 1 backend: pausa cierra sesion, retoma crea nueva sesion
-- Objetivo:
--   1) Mantener compatibilidad de nombres RPC actuales
--   2) Separar pausa operativa de incidencia
--   3) Permitir que otro operador retome un trabajo pausado
--   4) No tocar frontend, reportes ni ACABADOS en esta fase
--
-- Orden recomendado de ejecucion:
--   1) Ejecutar este archivo completo
--   2) Ejecutar db/migrations/2026-03-24_operator_pause_resume_level1_backend_validate.sql
--   3) Si algo falla y aun no se usa el nuevo flujo, ejecutar el rollback funcional

begin;

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 1) registro_produccion: columnas nuevas para enlazar sesiones y separar pausa
-- ---------------------------------------------------------------------------
alter table if exists public.registro_produccion
  add column if not exists flujo_trabajo_id uuid,
  add column if not exists retoma_de_registro_id bigint,
  add column if not exists motivo_pausa text,
  add column if not exists obs_pausa text,
  add column if not exists pausado_en timestamptz;

update public.registro_produccion
set flujo_trabajo_id = gen_random_uuid()
where flujo_trabajo_id is null;

alter table if exists public.registro_produccion
  alter column flujo_trabajo_id set default gen_random_uuid();

alter table if exists public.registro_produccion
  alter column flujo_trabajo_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'registro_produccion_retoma_de_fkey'
      and conrelid = 'public.registro_produccion'::regclass
  ) then
    alter table public.registro_produccion
      add constraint registro_produccion_retoma_de_fkey
      foreign key (retoma_de_registro_id)
      references public.registro_produccion(id)
      on delete set null;
  end if;
end;
$$;

-- ---------------------------------------------------------------------------
-- 2) orden_juegos_tr: permitir estado PAUSADO para T+R
-- ---------------------------------------------------------------------------
alter table if exists public.orden_juegos_tr
  drop constraint if exists orden_juegos_tr_estado_check;

alter table if exists public.orden_juegos_tr
  add constraint orden_juegos_tr_estado_check
  check (estado in ('PENDIENTE', 'PAUSADO', 'EN_PROCESO', 'FINALIZADO'));

-- ---------------------------------------------------------------------------
-- 3) Tabla nueva para incidencias separadas de la pausa operativa
-- ---------------------------------------------------------------------------
create table if not exists public.registro_produccion_incidencias (
  id bigint generated by default as identity primary key,
  registro_id bigint not null references public.registro_produccion(id) on delete cascade,
  flujo_trabajo_id uuid not null,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  orden_juego_id bigint references public.orden_juegos_tr(id) on delete set null,
  user_id uuid not null references public.profiles(id) on delete restrict,
  motivo text not null,
  observacion text,
  created_at timestamptz not null default now()
);

create index if not exists idx_rpi_registro
  on public.registro_produccion_incidencias(registro_id);

create index if not exists idx_rpi_flujo
  on public.registro_produccion_incidencias(flujo_trabajo_id);

create index if not exists idx_rpi_orden
  on public.registro_produccion_incidencias(orden_id);

create index if not exists idx_rpi_user
  on public.registro_produccion_incidencias(user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- 4) Backfill de registros PAUSADO legacy
--    Antes: PAUSADO seguia abierto.
--    Ahora: PAUSADO queda cerrado y listo para retoma.
-- ---------------------------------------------------------------------------
update public.registro_produccion
set
  motivo_pausa = coalesce(motivo_pausa, nullif(trim(coalesce(motivo_incidencia, '')), '')),
  obs_pausa = coalesce(obs_pausa, nullif(trim(coalesce(obs_incidencia, '')), '')),
  pausado_en = coalesce(pausado_en, hora_pausa, hora_fin, now())
where estado_registro = 'PAUSADO';

update public.registro_produccion
set
  hora_pausa = coalesce(hora_pausa, pausado_en, now()),
  hora_fin = coalesce(hora_fin, pausado_en, now())
where estado_registro = 'PAUSADO'
  and hora_fin is null;

update public.orden_juegos_tr j
set estado = 'PAUSADO'
where j.estado <> 'FINALIZADO'
  and exists (
    select 1
    from public.registro_produccion rp
    where rp.orden_juego_id = j.id
      and rp.estado_registro = 'PAUSADO'
  )
  and not exists (
    select 1
    from public.registro_produccion rp
    where rp.orden_juego_id = j.id
      and rp.estado_registro = 'ACTIVO'
      and rp.hora_fin is null
  );

-- ---------------------------------------------------------------------------
-- 5) Indices de seguridad para evitar doble retoma o doble activo normal
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (
    select 1
    from (
      select orden_id
      from public.registro_produccion
      where hora_fin is null
        and estado_registro = 'ACTIVO'
        and juego_num is null
      group by orden_id
      having count(*) > 1
    ) t
  ) then
    raise exception 'No se puede crear uq_registro_activo_normal_por_orden: hay ordenes normales con mas de un registro ACTIVO abierto.';
  end if;
end;
$$;

create unique index if not exists uq_registro_retoma_origen
  on public.registro_produccion(retoma_de_registro_id)
  where retoma_de_registro_id is not null;

create unique index if not exists uq_registro_activo_normal_por_orden
  on public.registro_produccion(orden_id)
  where hora_fin is null
    and estado_registro = 'ACTIVO'
    and juego_num is null;

-- ---------------------------------------------------------------------------
-- 6) RPC: pausar_trabajo
--    Nuevo comportamiento:
--      - cierra la sesion actual
--      - registra motivo/obs como pausa operativa
--      - deja el trabajo listo para retomar
--    Compatibilidad:
--      - mantiene el mismo nombre y firma
-- ---------------------------------------------------------------------------
create or replace function public.pausar_trabajo(
  p_registro_id bigint,
  p_motivo_incidencia text,
  p_obs_incidencia text default null
)
returns table (
  registro_id bigint,
  orden_id bigint,
  estado_registro text,
  nuevo_estado text,
  mensaje text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_orden_id bigint;
  v_orden_juego_id bigint;
  v_juego_num integer;
  v_cara text;
  v_pausa_ts timestamptz := now();
begin
  if v_user is null then
    raise exception 'Usuario no autenticado.';
  end if;

  if p_registro_id is null or p_registro_id <= 0 then
    raise exception 'registro_id invalido.';
  end if;

  select
    rp.orden_id,
    rp.orden_juego_id,
    rp.juego_num,
    rp.cara_impresion
  into
    v_orden_id,
    v_orden_juego_id,
    v_juego_num,
    v_cara
  from public.registro_produccion rp
  where rp.id = p_registro_id
    and rp.user_id = v_user
    and rp.hora_fin is null
    and rp.estado_registro = 'ACTIVO'
  limit 1;

  if v_orden_id is null then
    raise exception 'No existe registro ACTIVO para pausar (o no pertenece al usuario actual).';
  end if;

  update public.registro_produccion
  set
    estado_registro = 'PAUSADO',
    hora_pausa = v_pausa_ts,
    pausado_en = v_pausa_ts,
    hora_fin = v_pausa_ts,
    motivo_pausa = nullif(trim(coalesce(p_motivo_incidencia, '')), ''),
    obs_pausa = nullif(trim(coalesce(p_obs_incidencia, '')), '')
  where id = p_registro_id;

  if v_orden_juego_id is not null then
    update public.orden_juegos_tr
    set estado = 'PAUSADO'
    where id = v_orden_juego_id
      and estado <> 'FINALIZADO';
  end if;

  update public.ordenes
  set estado = 'IMPRESION'
  where id = v_orden_id
    and upper(estado::text) in ('PLACAS', 'DISENO', 'IMPRESION');

  registro_id := p_registro_id;
  orden_id := v_orden_id;
  estado_registro := 'PAUSADO';
  nuevo_estado := 'IMPRESION';
  mensaje := format(
    'Trabajo pausado y cerrado para retoma. Juego %s %s.',
    coalesce(v_juego_num::text, '-'),
    coalesce(v_cara, '-')
  );
  return next;
end;
$$;

-- ---------------------------------------------------------------------------
-- 7) RPC nueva: retomar_trabajo
--    Crea una nueva sesion enlazada a la sesion pausada anterior.
-- ---------------------------------------------------------------------------
create or replace function public.retomar_trabajo(
  p_registro_id bigint,
  p_maquina_id bigint default null
)
returns table (
  registro_id bigint,
  orden_id bigint,
  juego_num integer,
  cara text,
  estado_registro text,
  nuevo_estado text,
  mensaje text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_source_id bigint;
  v_orden_id bigint;
  v_maquina_id bigint;
  v_orden_juego_id bigint;
  v_juego_num integer;
  v_cara text;
  v_flujo_trabajo_id uuid;
  v_nuevo_registro_id bigint;
begin
  if v_user is null then
    raise exception 'Usuario no autenticado.';
  end if;

  if p_registro_id is null or p_registro_id <= 0 then
    raise exception 'registro_id invalido.';
  end if;

  select
    rp.id,
    rp.orden_id,
    rp.maquina_id,
    rp.orden_juego_id,
    rp.juego_num,
    rp.cara_impresion,
    rp.flujo_trabajo_id
  into
    v_source_id,
    v_orden_id,
    v_maquina_id,
    v_orden_juego_id,
    v_juego_num,
    v_cara,
    v_flujo_trabajo_id
  from public.registro_produccion rp
  where rp.id = p_registro_id
    and rp.estado_registro = 'PAUSADO'
  for update;

  if v_source_id is null then
    raise exception 'No existe registro PAUSADO para retomar.';
  end if;

  if exists (
    select 1
    from public.registro_produccion rp
    where rp.user_id = v_user
      and rp.hora_fin is null
      and rp.estado_registro = 'ACTIVO'
  ) then
    raise exception 'Ya tienes un registro ACTIVO. Finalizalo o pausalo antes de retomar otro.';
  end if;

  if exists (
    select 1
    from public.registro_produccion rp
    where rp.retoma_de_registro_id = v_source_id
  ) then
    raise exception 'Ese trabajo pausado ya fue retomado por otro operador.';
  end if;

  if v_juego_num is null then
    if exists (
      select 1
      from public.registro_produccion rp
      where rp.orden_id = v_orden_id
        and rp.juego_num is null
        and rp.hora_fin is null
        and rp.estado_registro = 'ACTIVO'
    ) then
      raise exception 'La orden ya tiene un registro ACTIVO.';
    end if;
  else
    if exists (
      select 1
      from public.registro_produccion rp
      where rp.orden_id = v_orden_id
        and rp.juego_num = v_juego_num
        and rp.hora_fin is null
        and rp.estado_registro = 'ACTIVO'
    ) then
      raise exception 'Ese juego ya tiene un registro ACTIVO.';
    end if;
  end if;

  begin
    insert into public.registro_produccion (
      orden_id,
      user_id,
      maquina_id,
      hora_inicio,
      estado_registro,
      orden_juego_id,
      juego_num,
      cara_impresion,
      flujo_trabajo_id,
      retoma_de_registro_id
    )
    values (
      v_orden_id,
      v_user,
      coalesce(p_maquina_id, v_maquina_id),
      now(),
      'ACTIVO',
      v_orden_juego_id,
      v_juego_num,
      v_cara,
      v_flujo_trabajo_id,
      v_source_id
    )
    returning id into v_nuevo_registro_id;
  exception
    when unique_violation then
      raise exception 'Ese trabajo pausado ya fue retomado o ya existe otra sesion ACTIVA para la misma unidad.';
  end;

  if v_orden_juego_id is not null then
    update public.orden_juegos_tr
    set estado = 'EN_PROCESO'
    where id = v_orden_juego_id
      and estado <> 'FINALIZADO';
  end if;

  update public.ordenes
  set estado = 'IMPRESION'
  where id = v_orden_id
    and upper(estado::text) in ('PLACAS', 'DISENO', 'IMPRESION');

  registro_id := v_nuevo_registro_id;
  orden_id := v_orden_id;
  juego_num := v_juego_num;
  cara := v_cara;
  estado_registro := 'ACTIVO';
  nuevo_estado := 'IMPRESION';
  mensaje := format(
    'Trabajo retomado correctamente. Juego %s %s.',
    coalesce(v_juego_num::text, '-'),
    coalesce(v_cara, '-')
  );
  return next;
end;
$$;

-- ---------------------------------------------------------------------------
-- 8) Wrapper de compatibilidad: reanudar_trabajo -> retomar_trabajo
--    Se mantiene para no romper clientes actuales.
-- ---------------------------------------------------------------------------
create or replace function public.reanudar_trabajo(
  p_registro_id bigint
)
returns table (
  registro_id bigint,
  orden_id bigint,
  estado_registro text,
  nuevo_estado text,
  mensaje text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select
    t.registro_id,
    t.orden_id,
    t.estado_registro,
    t.nuevo_estado,
    t.mensaje
  from public.retomar_trabajo(p_registro_id, null) t;
end;
$$;

-- ---------------------------------------------------------------------------
-- 9) RPC nueva: registrar_incidencia_produccion
--    Separa la incidencia del flujo de pausa operativa.
-- ---------------------------------------------------------------------------
create or replace function public.registrar_incidencia_produccion(
  p_registro_id bigint,
  p_motivo text,
  p_observacion text default null
)
returns table (
  incidencia_id bigint,
  registro_id bigint,
  orden_id bigint,
  mensaje text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_registro_id bigint;
  v_orden_id bigint;
  v_orden_juego_id bigint;
  v_flujo_trabajo_id uuid;
begin
  if v_user is null then
    raise exception 'Usuario no autenticado.';
  end if;

  if p_registro_id is null or p_registro_id <= 0 then
    raise exception 'registro_id invalido.';
  end if;

  if nullif(trim(coalesce(p_motivo, '')), '') is null then
    raise exception 'Motivo de incidencia obligatorio.';
  end if;

  select
    rp.id,
    rp.orden_id,
    rp.orden_juego_id,
    rp.flujo_trabajo_id
  into
    v_registro_id,
    v_orden_id,
    v_orden_juego_id,
    v_flujo_trabajo_id
  from public.registro_produccion rp
  where rp.id = p_registro_id
    and rp.user_id = v_user
  limit 1;

  if v_registro_id is null then
    raise exception 'No existe registro valido para registrar incidencia (o no pertenece al usuario actual).';
  end if;

  insert into public.registro_produccion_incidencias (
    registro_id,
    flujo_trabajo_id,
    orden_id,
    orden_juego_id,
    user_id,
    motivo,
    observacion
  )
  values (
    v_registro_id,
    v_flujo_trabajo_id,
    v_orden_id,
    v_orden_juego_id,
    v_user,
    trim(p_motivo),
    nullif(trim(coalesce(p_observacion, '')), '')
  )
  returning id into incidencia_id;

  registro_id := v_registro_id;
  orden_id := v_orden_id;
  mensaje := 'Incidencia registrada correctamente.';
  return next;
end;
$$;

grant execute on function public.pausar_trabajo(bigint, text, text) to authenticated;
grant execute on function public.retomar_trabajo(bigint, bigint) to authenticated;
grant execute on function public.reanudar_trabajo(bigint) to authenticated;
grant execute on function public.registrar_incidencia_produccion(bigint, text, text) to authenticated;

commit;
