-- Migration: T+R by game/cara (strict pair model)
-- Safe to run multiple times.
-- Recommended: run after taking Supabase backup/PITR checkpoint.

begin;

-- 1) Extend detalles_orden with T+R metadata used by admin form
alter table if exists public.detalles_orden
  add column if not exists requiere_juegos_placa boolean not null default false,
  add column if not exists juegos_placa_total integer,
  add column if not exists juegos_placa_detalle jsonb;

alter table if exists public.detalles_orden
  drop constraint if exists detalles_orden_juegos_placa_total_chk;

alter table if exists public.detalles_orden
  add constraint detalles_orden_juegos_placa_total_chk
  check (juegos_placa_total is null or juegos_placa_total >= 2);

-- 2) Normalized table for T+R game sides
create table if not exists public.orden_juegos_tr (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes(id) on delete cascade,
  juego_num integer not null check (juego_num >= 1),
  cara text not null check (cara in ('TIRA', 'RETIRA')),
  nombre text not null,
  cantidad_objetivo integer check (cantidad_objetivo is null or cantidad_objetivo >= 0),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'EN_PROCESO', 'FINALIZADO')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (orden_id, juego_num, cara)
);

create index if not exists idx_orden_juegos_tr_orden on public.orden_juegos_tr(orden_id);
create index if not exists idx_orden_juegos_tr_estado on public.orden_juegos_tr(estado);

-- 3) Add per-game fields into registro_produccion for traceability by operador/cara
alter table if exists public.registro_produccion
  add column if not exists orden_juego_id bigint references public.orden_juegos_tr(id) on delete set null,
  add column if not exists juego_num integer,
  add column if not exists cara_impresion text,
  add column if not exists buena_reportada integer,
  add column if not exists mala_reportada integer;

alter table if exists public.registro_produccion
  drop constraint if exists registro_produccion_cara_impresion_chk;

alter table if exists public.registro_produccion
  add constraint registro_produccion_cara_impresion_chk
  check (cara_impresion is null or cara_impresion in ('TIRA', 'RETIRA'));

alter table if exists public.registro_produccion
  drop constraint if exists registro_produccion_buena_reportada_chk;

alter table if exists public.registro_produccion
  add constraint registro_produccion_buena_reportada_chk
  check (buena_reportada is null or buena_reportada >= 0);

alter table if exists public.registro_produccion
  drop constraint if exists registro_produccion_mala_reportada_chk;

alter table if exists public.registro_produccion
  add constraint registro_produccion_mala_reportada_chk
  check (mala_reportada is null or mala_reportada >= 0);

-- If juego_num is provided, cara_impresion must exist too.
alter table if exists public.registro_produccion
  drop constraint if exists registro_produccion_juego_cara_pair_chk;

alter table if exists public.registro_produccion
  add constraint registro_produccion_juego_cara_pair_chk
  check ((juego_num is null and cara_impresion is null) or (juego_num is not null and cara_impresion is not null));

-- Concurrency lock: no two active registros for same orden+juego+cara
drop index if exists public.uq_registro_abierto_por_orden;

create unique index if not exists uq_registro_activo_por_juego_cara
  on public.registro_produccion (orden_id, juego_num, cara_impresion)
  where hora_fin is null and juego_num is not null and cara_impresion is not null;

-- 4) Helper trigger to keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_orden_juegos_tr_updated_at on public.orden_juegos_tr;
create trigger trg_orden_juegos_tr_updated_at
before update on public.orden_juegos_tr
for each row execute function public.set_updated_at();

-- 5) Sync normalized games from detalles_orden JSON metadata
create or replace function public.sync_orden_juegos_tr_from_detalle(p_orden_id bigint)
returns void
language plpgsql
as $$
declare
  det record;
  total_juegos integer;
  i integer;
  item jsonb;
  v_cara text;
  v_nombre text;
  cant integer;
begin
  select
    orden_id,
    requiere_juegos_placa,
    coalesce(juegos_placa_total, 0) as juegos_placa_total,
    coalesce(juegos_placa_detalle, '[]'::jsonb) as juegos_placa_detalle,
    cantidad_solicitada
  into det
  from public.detalles_orden
  where orden_id = p_orden_id
  limit 1;

  if not found then
    return;
  end if;

  if coalesce(det.requiere_juegos_placa, false) = false then
    delete from public.orden_juegos_tr where orden_id = p_orden_id;
    return;
  end if;

  total_juegos := greatest(coalesce(det.juegos_placa_total, 2), 2);
  cant := det.cantidad_solicitada;

  -- Rebuild rows to keep strict sync with admin definition
  delete from public.orden_juegos_tr where orden_id = p_orden_id;

  if jsonb_typeof(det.juegos_placa_detalle) = 'array' and jsonb_array_length(det.juegos_placa_detalle) > 0 then
    for item in
      select value from jsonb_array_elements(det.juegos_placa_detalle)
    loop
      i := coalesce((item->>'orden')::int, null);
      if i is null then
        continue;
      end if;
      v_cara := upper(coalesce(item->>'cara', case when mod(i, 2) = 1 then 'TIRA' else 'RETIRA' end));
      v_nombre := nullif(trim(coalesce(item->>'nombre', '')), '');
      if v_nombre is null then
        v_nombre := format('%s %s%s', v_cara, ceil(i::numeric / 2)::int, case when mod(i, 2) = 1 then 'A' else 'B' end);
      end if;

      insert into public.orden_juegos_tr (orden_id, juego_num, cara, nombre, cantidad_objetivo)
      values (p_orden_id, ceil(i::numeric / 2)::int, v_cara, v_nombre, cant)
      on conflict (orden_id, juego_num, cara)
      do update set
        nombre = excluded.nombre,
        cantidad_objetivo = excluded.cantidad_objetivo,
        updated_at = now();
    end loop;
  else
    -- Fallback auto-build if JSON absent
    for i in 1..total_juegos loop
      v_cara := case when mod(i, 2) = 1 then 'TIRA' else 'RETIRA' end;
      v_nombre := format('%s %s%s', v_cara, ceil(i::numeric / 2)::int, case when mod(i, 2) = 1 then 'A' else 'B' end);

      insert into public.orden_juegos_tr (orden_id, juego_num, cara, nombre, cantidad_objetivo)
      values (p_orden_id, ceil(i::numeric / 2)::int, v_cara, v_nombre, cant)
      on conflict (orden_id, juego_num, cara)
      do update set
        nombre = excluded.nombre,
        cantidad_objetivo = excluded.cantidad_objetivo,
        updated_at = now();
    end loop;
  end if;
end;
$$;

create or replace function public.trg_sync_orden_juegos_tr_from_detalle()
returns trigger
language plpgsql
as $$
begin
  perform public.sync_orden_juegos_tr_from_detalle(new.orden_id);
  return new;
end;
$$;

drop trigger if exists trg_detalles_sync_orden_juegos_tr on public.detalles_orden;
create trigger trg_detalles_sync_orden_juegos_tr
after insert or update of requiere_juegos_placa, juegos_placa_total, juegos_placa_detalle, cantidad_solicitada
on public.detalles_orden
for each row
execute function public.trg_sync_orden_juegos_tr_from_detalle();

-- Backfill for existing orders already marked with juegos metadata
do $$
declare
  r record;
begin
  for r in
    select orden_id
    from public.detalles_orden
    where coalesce(requiere_juegos_placa, false) = true
  loop
    perform public.sync_orden_juegos_tr_from_detalle(r.orden_id);
  end loop;
end;
$$;

-- 6) Consolidated view by game pair (strict TIRA/RETIRA)
create or replace view public.v_orden_juegos_tr_consolidado as
with agg as (
  select
    rp.orden_id,
    rp.juego_num,
    rp.cara_impresion,
    sum(coalesce(rp.buena_reportada, rp.cantidad_buena, 0)) as buena,
    sum(coalesce(rp.mala_reportada, rp.cantidad_mala, 0)) as mala,
    max(rp.hora_fin) as ultima_hora_fin
  from public.registro_produccion rp
  where rp.juego_num is not null
    and rp.cara_impresion in ('TIRA', 'RETIRA')
  group by rp.orden_id, rp.juego_num, rp.cara_impresion
)
select
  j.orden_id,
  j.juego_num,
  max(case when j.cara = 'TIRA' then j.nombre end) as nombre_tira,
  max(case when j.cara = 'RETIRA' then j.nombre end) as nombre_retira,
  coalesce(max(case when a.cara_impresion = 'TIRA' then a.buena end), 0) as buena_tira,
  coalesce(max(case when a.cara_impresion = 'RETIRA' then a.buena end), 0) as buena_retira,
  coalesce(max(case when a.cara_impresion = 'TIRA' then a.mala end), 0) as mala_tira,
  coalesce(max(case when a.cara_impresion = 'RETIRA' then a.mala end), 0) as mala_retira,
  least(
    coalesce(max(case when a.cara_impresion = 'TIRA' then a.buena end), 0),
    coalesce(max(case when a.cara_impresion = 'RETIRA' then a.buena end), 0)
  ) as buena_final_par,
  greatest(
    coalesce(max(case when j.cara = 'TIRA' then j.cantidad_objetivo end), 0) -
    least(
      coalesce(max(case when a.cara_impresion = 'TIRA' then a.buena end), 0),
      coalesce(max(case when a.cara_impresion = 'RETIRA' then a.buena end), 0)
    ),
    0
  ) as mala_final_par,
  max(case when j.cara = 'TIRA' then j.cantidad_objetivo end) as cantidad_objetivo_par,
  max(case when a.cara_impresion = 'TIRA' then a.ultima_hora_fin end) as fin_tira,
  max(case when a.cara_impresion = 'RETIRA' then a.ultima_hora_fin end) as fin_retira
from public.orden_juegos_tr j
left join agg a
  on a.orden_id = j.orden_id
 and a.juego_num = j.juego_num
 and a.cara_impresion = j.cara
group by j.orden_id, j.juego_num;

commit;
